# Generated by Django 4.2.2 on 2023-06-16 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("grid1", models.BinaryField(default=b"\x08", max_length=100)),
                ("grid2", models.BinaryField(default=b"\x08", max_length=100)),
                ("player", models.IntegerField(default=0)),
                ("steps", models.IntegerField(default=0)),
                ("winner", models.CharField(default=0, max_length=100)),
            ],
        ),
    ]
