# Generated by Django 4.2.2 on 2023-06-16 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="left",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="player",
            name="right",
            field=models.BooleanField(default=False),
        ),
    ]
