# Generated by Django 4.2.2 on 2023-06-16 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_player_left_player_right"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="left_choice",
            field=models.BinaryField(default=b"\x08", max_length=100),
        ),
        migrations.AddField(
            model_name="player",
            name="right_choice",
            field=models.BinaryField(default=b"\x08", max_length=100),
        ),
    ]
