# Generated by Django 4.2.2 on 2023-06-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_player_left_choice_player_right_choice"),
    ]

    operations = [
        migrations.RenameField(
            model_name="player",
            old_name="name",
            new_name="name1",
        ),
        migrations.AddField(
            model_name="player",
            name="name2",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
