# Generated by Django 4.2.2 on 2023-06-16 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_rename_name_player_name1_player_name2"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="message",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="player",
            name="winner",
            field=models.IntegerField(default=0),
        ),
    ]
