# Generated by Django 4.2.3 on 2023-09-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_player_message_alter_player_winner"),
    ]

    operations = [
        migrations.AddField(
            model_name="player",
            name="new_id",
            field=models.IntegerField(default=0),
        ),
    ]
